version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 99
  target-branch: develop
  ignore:
  - dependency-name: org.assertj:assertj-core
    versions:
    - 3.19.0
